name: Lint & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install aria2
      run: sudo apt-get install -y aria2
    - name: Start aria2 in RPC server mode
      run: |
        nohup aria2c --enable-rpc > /dev/null 2>&1 &
    - name: Lint with pylint
      run: |
        pylint --rcfile=.pylintrc **/*.py
    - name: Test with pytest
      run: |
        pytest
